- name: This playbook for Package Management
  hosts: 
    - linux

  pre_tasks:
    - debug: 
        msg: "Start Playbook"

  roles:
    - datadisk-n01521961
    - profile-n01521961
    - user-n01521961
    - webserver-n01521961

  post_tasks:
    - debug: 
        msg: "Playbook Completed Successfully"

